<a href="https://colab.research.google.com/github/lmaryemoralesnunez/Procesos-Estocasticos/blob/main/Tarea5Procesos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


EJERCICIO 3

In [1]:
import numpy as np
from math import exp, factorial, sqrt

# matriz R
R = np.array([
    [0,2,3,0],
    [4,0,2,0],
    [0,2,0,2],
    [1,0,3,0]
],dtype=float)

# r_i
ri = np.sum(R,axis=1)

# r=max(r_i)
r = np.max(ri)

print("r =",r)

# matriz P sombrero
P_hat = np.zeros_like(R)

for i in range(4):
    for j in range(4):
        if i==j:
            P_hat[i,j] = 1-ri[i]/r
        else:
            P_hat[i,j] = R[i,j]/r

print(P_hat)

r = 6.0
[[0.16666667 0.33333333 0.5        0.        ]
 [0.66666667 0.         0.33333333 0.        ]
 [0.         0.33333333 0.33333333 0.33333333]
 [0.16666667 0.         0.5        0.33333333]]


Función para calcular P(t)


In [2]:
def P_t(t):

    M = int(max(r*t + 5*np.sqrt(r*t),20))

    n = len(P_hat)

    P = np.zeros((n,n))

    for k in range(M+1):

        coef = exp(-r*t)*(r*t)**k/factorial(k)

        P += coef*np.linalg.matrix_power(P_hat,k)

    return P

Calculando

In [3]:
print("P(0.5)")
print(P_t(0.5))

print()

print("P(1)")
print(P_t(1))

print()

print("P(5)")
print(P_t(5))

P(0.5)
[[0.25060868 0.2169646  0.38665694 0.14576979]
 [0.25313484 0.23836098 0.37440924 0.13409493]
 [0.1691195  0.19361489 0.42030102 0.2169646 ]
 [0.15801748 0.15744464 0.39833179 0.28620609]]

P(1)
[[0.20615112 0.20390203 0.3987096  0.1912358 ]
 [0.20828421 0.2053407  0.39789917 0.18847446]
 [0.19675849 0.19837934 0.40095869 0.20390203]
 [0.19204622 0.19399715 0.40147094 0.21248423]]

P(5)
[[0.19999925 0.19999925 0.3999985  0.19999925]
 [0.19999925 0.19999925 0.3999985  0.19999925]
 [0.19999925 0.19999925 0.3999985  0.19999925]
 [0.19999925 0.19999925 0.3999985  0.19999925]]


Chapman-Kolmogorov

In [4]:
P05 = P_t(0.5)
P1 = P_t(1)

print(P1)

print()

print(P05 @ P05)

[[0.20615112 0.20390203 0.3987096  0.1912358 ]
 [0.20828421 0.2053407  0.39789917 0.18847446]
 [0.19675849 0.19837934 0.40095869 0.20390203]
 [0.19204622 0.19399715 0.40147094 0.21248423]]

[[0.20615141 0.20390232 0.39871018 0.19123609]
 [0.20828451 0.20534099 0.39789976 0.18847475]
 [0.19675878 0.19837963 0.40095927 0.20390232]
 [0.19204651 0.19399744 0.40147152 0.21248452]]


EJERCICIO 4

Algoritmo de Uniformización para calcular P(t)

In [5]:
import numpy as np

def uniformizacion(R, t, epsilon=1e-5):

    # Paso 1: calcular r
    r = np.max(np.sum(R, axis=1))

    # Paso 2: construir P_hat
    n = R.shape[0]
    P_hat = np.zeros((n,n))

    for i in range(n):
        ri = np.sum(R[i,:])

        for j in range(n):

            if i == j:
                P_hat[i,j] = 1 - ri/r
            else:
                P_hat[i,j] = R[i,j]/r

    # Paso 3: inicialización
    A = P_hat.copy()

    B = np.exp(-r*t)*np.eye(n)

    c = np.exp(-r*t)

    suma = c

    k = 1

    # Paso 4: ciclo principal
    while suma < 1 - epsilon:

        c = c*(r*t)/k

        B = B + c*A

        A = A @ P_hat

        suma += c

        k += 1

    return B, k-1

In [6]:
R = np.array([
    [0,2,3,0],
    [4,0,2,0],
    [0,2,0,2],
    [1,0,3,0]
], dtype=float)

In [7]:
P05, M05 = uniformizacion(R, 0.5)

print("M utilizado =", M05)
print(P05)

M utilizado = 13
[[0.250608   0.21696392 0.38665557 0.14576911]
 [0.25313416 0.2383603  0.37440788 0.13409425]
 [0.16911882 0.19361421 0.42029966 0.21696392]
 [0.1580168  0.15744396 0.39833043 0.28620541]]


In [8]:
P1, M1 = uniformizacion(R, 1)

print("M utilizado =", M1)
print(P1)

M utilizado = 19
[[0.20615038 0.20390128 0.39870811 0.19123506]
 [0.20828347 0.20533995 0.39789768 0.18847371]
 [0.19675775 0.19837859 0.4009572  0.20390128]
 [0.19204548 0.1939964  0.40146945 0.21248349]]


In [9]:
P5, M5 = uniformizacion(R, 5)

print("M utilizado =", M5)
print(P5)

M utilizado = 56
[[0.19999853 0.19999853 0.39999705 0.19999852]
 [0.19999853 0.19999853 0.39999705 0.19999852]
 [0.19999852 0.19999852 0.39999705 0.19999853]
 [0.19999852 0.19999852 0.39999705 0.19999853]]


Verificar Chapman-Kolmogorov

In [10]:
izquierda = P1

derecha = P05 @ P05

print("P(1):")
print(izquierda)

print("\nP(0.5)P(0.5):")
print(derecha)

print("\nError máximo:")
print(np.max(np.abs(izquierda - derecha)))

P(1):
[[0.20615038 0.20390128 0.39870811 0.19123506]
 [0.20828347 0.20533995 0.39789768 0.18847371]
 [0.19675775 0.19837859 0.4009572  0.20390128]
 [0.19204548 0.1939964  0.40146945 0.21248349]]

P(0.5)P(0.5):
[[0.20615005 0.20390096 0.39870746 0.19123473]
 [0.20828314 0.20533963 0.39789704 0.18847339]
 [0.19675742 0.19837827 0.40095655 0.20390096]
 [0.19204515 0.19399608 0.4014688  0.21248316]]

Error máximo:
6.494595712336348e-07


EJERCICIO 6

In [11]:
izquierda = P1

In [12]:
derecha = P05 @ P05

In [13]:
print("P(1):")
print(izquierda)

P(1):
[[0.20615038 0.20390128 0.39870811 0.19123506]
 [0.20828347 0.20533995 0.39789768 0.18847371]
 [0.19675775 0.19837859 0.4009572  0.20390128]
 [0.19204548 0.1939964  0.40146945 0.21248349]]


In [14]:
print("\nP(0.5)P(0.5):")
print(derecha)


P(0.5)P(0.5):
[[0.20615005 0.20390096 0.39870746 0.19123473]
 [0.20828314 0.20533963 0.39789704 0.18847339]
 [0.19675742 0.19837827 0.40095655 0.20390096]
 [0.19204515 0.19399608 0.4014688  0.21248316]]


In [15]:
print("\nError máximo:")
print(np.max(np.abs(izquierda - derecha)))


Error máximo:
6.494595712336348e-07


Se verificó numéricamente la ecuación de Chapman-Kolmogorov comparando la matriz P(1) obtenida mediante uniformización con el producto P(0.5)P(0.5). El error máximo obtenido fue del orden de 10
−6
 (o el valor que te salga), lo que confirma la validez de la aproximación y de la propiedad semigrupo de las matrices de transición de una CMTC.